on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: postidev.azurecr.io
        username: ${{ secrets.acr_postidev_username }}
        password: ${{ secrets.acr_postidev_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t postidev.azurecr.io/devcluster:${{ github.sha }}
        docker push postidev.azurecr.io/devcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_devcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep devcluster81a6 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace devcluster81a6`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: devcluster81a6
        container-registry-url: postidev.azurecr.io
        container-registry-username: ${{ secrets.acr_postidev_username }}
        container-registry-password: ${{ secrets.acr_postidev_password }}
        secret-name: devclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: devcluster81a6
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress.yml
        images: |
          postidev.azurecr.io/devcluster:${{ github.sha }}
        imagepullsecrets: |
          devclusterdockerauth